# Generated by Django 3.2.16 on 2022-10-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_coin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='Currency',
        ),
    ]
