name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build containers
      run: docker-compose up -d

    - name: Test Methods
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 20
        command: docker compose exec bank-django-service bash ./Test

